### ISSUE TITLE
[Feature]: Workflow Docker Push

### ISSUE THREAD

**Issue by tamaskan** [avoonix/material-e621#11]
### Description

Auto-Push the Docker-Image

Example: https://github.com/tamaskan/material-e621/blob/master/.github/workflows/docker-upload.yml

based on: https://medium.com/platformer-blog/lets-publish-a-docker-image-to-docker-hub-using-a-github-action-f0b17e5cceb3

**Comment by avoonix** [comment]
Causes following error: `Error: Cannot perform an interactive login from a non TTY device`

This one works: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
