### ISSUE TITLE
[Feature]: Gallery-View for favorites

### ISSUE THREAD

**Issue by tamaskan** [avoonix/material-e621#17]
### Description

I think having a menu-item to view all favorite images/videos would be useful, since the original site has that too

**Comment by avoonix** [comment]
before add:
![Screenshot_20230708_090726](https://github.com/avoonix/material-e621/assets/63160225/177037d8-102a-4d40-a947-5c760a69a2ee)
before remove:
![Screenshot_20230708_090740](https://github.com/avoonix/material-e621/assets/63160225/97e263d5-64b3-4ce7-bfa3-da52b480507c)
