### ISSUE TITLE
[Bug]: Order tags stop working after the first page.

### ISSUE THREAD

**Issue by FA5556** [avoonix/material-e621#19]
### Expected Behavior

Tags like order:score and order:favcount continue to place posts in order after the first page.

### Actual Behavior

Tags like order:score and order:favcount seem to stop working after loading the second page

### Steps to Reproduce the Problem

Search for something like order:score or order:favcount, scroll down and load the next page either manually or automatically

**Comment by avoonix** [comment]
This will take longer to fix. I am currently using a/b + post id to paginate, which overrides the sorting.

From https://e621.net/help/api:
> `page` The page that will be returned. Can also be used with a or b + post_id to get the posts after or before the specified post ID. For example a13 gets every post after post_id 13 up to the limit. This overrides any ordering meta-tag, order:id_desc is always used instead.

A workaround for now would be to set the page size in settings to a higher value, but that only works for the first 320 posts.

**Comment by avoonix** [comment]
This is now fixed. I am now no longer using `a`/`b` for pagination; this might cause some shifts in posts - eg if you open the same page a few days apart, there might be completely different posts now; but this is also what e6 does, so it should be alright.
