### ISSUE TITLE
[Feature]: Some Ideas 

### ISSUE THREAD

**Issue by tamaskan** [avoonix/material-e621#2]
### Description

1) Docker-Container on hub.docker.com
2) Integrate e621-dl (eg. auto download favorites/pool)
3) Gallery with all downloaded Files
3) Apprise-Integration (eg. follow artists and notify when there are new submissions)

**Comment by avoonix** [comment]
I don't see the benefit of integrating with e621-dl (or any other gallery downloader). But if we complete #1, we can have a downloader built-in. It's not possible to do this with the current web version because of CORS.

**Comment by avoonix** [comment]
Thanks for the suggestions. I forgot to I add the suggestion to create separate issues for each feature in the template. It's now updated and I also divided your suggestions into separate issues.  Don't forget to subscribe to them if you want to receive notifications.
