### ISSUE TITLE
[Bug]: Tag Limit of 6 when API should support up to 40

### ISSUE THREAD

**Issue by Temmie-Flakes** [avoonix/material-e621#20]
### Expected Behavior

something like "anthro male fur tail claws clothing" would have many results but "anthro male fur tail claws clothing touching_cheek" would have roughly 3 results.

### Actual Behavior

It ignores the last index of tags and only uses the first 6.  And in the example of "anthro male fur tail claws clothing touching_cheek" it produces several thousand results rather then just the 3 it should.

### Steps to Reproduce the Problem

type "anthro male fur tail claws clothing touching_cheek" in material search bar......
I believe [createTagQuery.ts](https://github.com/avoonix/material-e621/blob/18e525c2cee32f767bb4926bcc1b58373465c7e4/src/misc/util/createTagQuery.ts#L62C3-L62C40)  
`return allTags.slice(0, 6).join(" ");`  
is what causes this.  

I know the API used to be at a 6 tag limit on the old system but its been updated to 40 so I assume it should be  
`return allTags.slice(0, 40).join(" ");`  
or just `return allTags` if the API calls can work with ones longer then 40.

I don't know if this is intentional or a workaround of something else, but I'm assuming its not desired to have fewer tags then what E6 can support.

**Comment by avoonix** [comment]
Changed it to 40 for now, as supplying more than that causes an error. 

I initially added the limit of 6 because going over that limit caused an error - this was easily achieved by adding a few blacklist tags, as I am merging the blacklist tags with the user's query.
