### ISSUE TITLE
[Feature]: Import blacklist

### ISSUE THREAD

**Issue by unknowner00** [avoonix/material-e621#21]
### Description

I am unsure if you could do this using the API key, so I won't focus on that here.

The blacklist is composed of elements, separated by line, which can be copied by the user.
This can easily be converted into the json file used by the importer.
Here is an example blacklist:
```
low_res
anthro -tail
standing
```
You can add quotes around every line,
```
"low_res"
"anthro -tail"
"standing"
```
Put a comma after every line, (except the last one)
```
"low_res",
"anthro -tail",
"standing"
```
Remove all line breaks,
```
"low_res","anthro -tail","standing"
```
And insert it into the blacklist section.
```
"blacklist":{"mode":0,"tags":["low_res","anthro -tail","standing"]}
```
Modifying the file like this, and importing it, has worked on my end.

**Comment by avoonix** [comment]
I can't deal with a group of tags (unless I missed something or the e6 API changed). This app just takes all tags from the blacklist and adds it to the query with `-` prepended, so the `anthro -tail` line will behave differently than on e6.

**Comment by avoonix** [comment]
Now it should work as expected. The previous blacklist settings will be converted to the new format automatically, but if you still have the `anthro -tail` as single tag, it will not work.

The new config should look like this:
```json
[
  ["low_res"],
  ["anthro", "-tail"],
  ["standing"]
]
```
(or you can use the importer)
