### ISSUE TITLE
[Bug]: Network error when logged in account 

### ISSUE THREAD

**Issue by Ururhduy** [avoonix/material-e621#22]
### Expected Behavior

I expect when I logged in my account I would be able to see hidden images 

### Actual Behavior

but instead I get network error pop up

### Steps to Reproduce the Problem

This happens when you log in you e621 account and APL key

**Comment by avoonix** [comment]
Did you double check if the username is correct (including caps) and the api key is 24 characters long?

**Comment by Ururhduy** [comment]
Yes and I tried but still did not work even when I do all caps

**Comment by avoonix** [comment]
Go to https://e621.net/users/home, select and copy your username, and paste it into Material e621. Make sure there is neither whitespace, nor the exclamation mark in the text field.
![image](https://github.com/avoonix/material-e621/assets/63160225/a9840c23-b916-4d43-8a11-93d3bf46e6f2)

On the same page, under "Manage API Access", copy the API key and paste it into Material e621.
![image](https://github.com/avoonix/material-e621/assets/63160225/2f842ca7-c600-4730-a4d8-05548a02e60a)

I have now added a "Verify credentials" button, which you can try. If it still doesn't work, you can press <kbd>F12</kbd> to open the browser developer tools. Go to the network tab and click the "Verify credentials" button again - you should see a new request. Right click and open it in a new tab, if you see anything other than the response below, report back to me (and make sure to not expose your API key).
```json
{
  "success": false,
  "message": "SessionLoader::AuthenticationFailure",
  "code": null
}
```
![image](https://github.com/avoonix/material-e621/assets/63160225/a58f4135-2b2c-4388-b0f7-008dab4f9f71)
![image](https://github.com/avoonix/material-e621/assets/63160225/8d5c99cb-4e6f-4f0a-b7d8-418ed85eb182)

**Comment by avoonix** [comment]
closing now
feel free to reopen if the issue persists
