### ISSUE TITLE
[Feature]: e6ai.net Support

### ISSUE THREAD

**Issue by Bitz** [avoonix/material-e621#26]
### Description

Surprise! There's a new instance of e621, directed firmly at AI generated art. Makes sense, keeps the main site clear of this form of art.

Hopefully adding support is as simple as adding a new item to that drop down. 

Thanks!

**Comment by avoonix** [comment]
> Hopefully adding support is as simple as adding a new item to that drop down.

Mostly yes, but favoriting and some tags don't work (they have director instead of artist, and also no lore or copyright tags). 

That's why I don't want to officially support it and just added a text field. Just paste in `https://e6ai.net/` underneath the select.

**Comment by avoonix** [comment]
(favoriting should work if you use your own proxy, see https://github.com/avoonix/material-e621/issues/25#issuecomment-1904969363)
