### ISSUE TITLE
[Feature]: add default tags

### ISSUE THREAD

**Issue by Cris-White-Fox** [avoonix/material-e621#28]
### Description

just like there is a blacklist that filters out all posts with blacklisted tags by default

but make the opposite tags mandatory in any search

I often have a lot of art for a tag and I have a list of additional tags that I add to each query manually. It would be convenient to add them automatically when the checkbox is checked.

**Comment by avoonix** [comment]
You can already kind of do this. You can add searches from your history to the sidebar:
![image](https://github.com/avoonix/material-e621/assets/63160225/4021581a-2ce4-44bd-bbcd-b84f4609de35)
![image](https://github.com/avoonix/material-e621/assets/63160225/d0f11e6c-a2b6-40a0-b3e6-52a2d0b610c7)

Unless there's another good reason to add this, I'm closing this issue for now.
