### ISSUE TITLE
[Feature]: Hot/Popular-Tab on the left Side

### ISSUE THREAD

**Issue by tamaskan** [avoonix/material-e621#6]
### Description

I don't know if that is possible via the api or if the pages must be parsed, but i think those are the most visited pages

**Comment by avoonix** [comment]
Hot is just a tag (`order:rank`), so it's already supported - although not very discoverable (yet)
Maybe something like this could help: 
![image](https://user-images.githubusercontent.com/63160225/214693515-31014e14-403d-4e98-bda1-8a7b173c4b8d.png)

Popular should probably be a separate page.

**Comment by avoonix** [comment]
Easier sorting has been added in 36e08de

**Comment by avoonix** [comment]
> If someone wants a tab, https://github.com/avoonix/material-e621/blob/1fb6a571fceb58727f13acd63451b0b64f4a3f38/src/App/navigation.ts is pretty close to the original (posts?tags=order:favcount date:today + posts?tags=order%3Arank)

Thanks for the suggestion; added those as defaults
