### ISSUE TITLE
[Bug]: Blacklisting Limitations

### ISSUE THREAD

**Issue by CLatte** [avoonix/material-e621#8]
### Expected Behavior

blacklist work properly and block post with blacklisted tag

### Actual Behavior

although most blacklist work as intended (e.g. blacklisting 'female' tag would hide all post with that tag), tag(s) like 'the_magnus_archive' does not get hidden

### Steps to Reproduce the Problem

1. open home (default settings)
2. scroll down, found post with 'the_magnus_archive' tag
3. click (i) button and find 'the_magnus_archive' tag
4. click the three-dots menu
5. click add to blacklist
6, refresh page with CTRL-R
7. post still available to be seen

Alternate option: Manually add the tag in the settings

**Comment by avoonix** [comment]
The tag `the_magnus_archive` doesn't exist, it's `the_magnus_archives` (with s at the end). Can you check if that's the problem?

Another possibility could be the tag limit. e621 only allows 6 tags in the query. If you choose the blacklist mode 'hide' and blacklist 3 tags, and your query contains 4 tags, then the last tag of the blacklist would be dropped. (I should probably explain that on the blacklist settings page) - I used to do client-side filtering in that case, but that caused other problems.

**Comment by avoonix** [comment]
> Another possibility could be the tag limit. e621 only allows 6 tags in the query. If you choose the blacklist mode 'hide' and blacklist 3 tags, and your query contains 4 tags, then the last tag of the blacklist would be dropped. (I should probably explain that on the blacklist settings page) - I used to do client-side filtering in that case, but that caused other problems.

The blacklist is now fully client-side (just like the original e621 one).
