### ISSUE TITLE
[Bug]: Network Error Brave

### ISSUE THREAD

**Issue by ANMJKNDI** [avoonix/material-e621#9]
### Expected Behavior

Being able to access the web application upon logging in

### Actual Behavior

network error upon logging in the API with an user's API key

I already tested it with google chrome and it works there, but not on other chromium browsers. 

The browser used was Brave

### Steps to Reproduce the Problem

1. open a chromium-based browser
2. Access web app
3. Browse posts
4. Open settings
5. Reach API access 
6. Log in with your account
7. Open Home tab

**Comment by avoonix** [comment]
should work with chromium browsers as well, possibly a captcha issue

if you still believe this is a bug, please submit a video reporducing the bug

**Comment by ANMJKNDI** [comment]
I tried the application on both chrome and brave. 
It worked fine on chrome, but had network errors on brave upon logging in

**Comment by avoonix** [comment]
- Does it work with brave shields turned off?
- Does it work in an incognito window with all extensions turned off?
- Can you export the settings from your chrome browser and import them into brave and try again? (Settings > Backup and Restore)
- What errors are shown in the developer tools (<kbd>F12</kbd> > Network)? ![Screenshot_20230501_210542](https://user-images.githubusercontent.com/63160225/235513102-b5678e61-9179-498b-b988-a3138f3d485f.png)

**Comment by ANMJKNDI** [comment]
I changed my username and now the application works just fine 
My username was formated as "Name_surname" I changed it to "NameSurname" and now it no longer gives me network errors
